from mars_patcher.constants.credits import LineType

MARS_CREDITS = [
    (LineType.WHITE_BIG, 4, "MARS Development"),
    (LineType.BLUE, 2, "PROGRAMMING"),
    (LineType.WHITE_BIG, 1, "AntyMew"),
    (LineType.WHITE_BIG, 1, "biospark"),
    (LineType.WHITE_BIG, 1, "cluekitty"),
    (LineType.WHITE_BIG, 1, "Zarakava"),
    (LineType.WHITE_BIG, 1, "Miepee"),
    (LineType.WHITE_BIG, 1, "JeffGainsNGames"),
    (LineType.WHITE_BIG, 3, "duncathan_salt"),
    (LineType.BLUE, 2, "GRAPHICS"),
    (LineType.WHITE_BIG, 1, "jakoliath"),
    (LineType.WHITE_BIG, 1, "AbyssalCreature"),
    (LineType.WHITE_BIG, 1, "bariasu"),
    (LineType.WHITE_BIG, 3, "Raddley Vance"),
    (LineType.BLUE, 2, "MUSIC"),
    (LineType.WHITE_BIG, 3, "JRP"),
    (LineType.BLUE, 2, "SPECIAL THANKS TO"),
    (LineType.WHITE_BIG, 1, "Yohann"),
    (LineType.WHITE_BIG, 2, "Kazuto"),
    (LineType.WHITE_BIG, 4, "And contributions from others"),
]

RDV_CREDITS = [
    (LineType.WHITE_BIG, 2, "Randovania"),
    (LineType.BLUE, 2, "INTEGRATION"),
    (LineType.WHITE_BIG, 1, "JeffGainsNGames"),
    (LineType.WHITE_BIG, 1, "Miepee"),
    (LineType.WHITE_BIG, 1, "m4rkersm4sk"),
    (LineType.WHITE_BIG, 3, "cluekitty"),
    (LineType.BLUE, 2, "LOGIC DATABASE"),
    (LineType.WHITE_BIG, 1, "cluekitty"),
    (LineType.WHITE_BIG, 1, "HerculesBenchPress"),
    (LineType.WHITE_BIG, 1, "HyperBola"),
    (LineType.WHITE_BIG, 1, "JaggerG"),
    (LineType.WHITE_BIG, 1, "JeffGainsNGames"),
    (LineType.WHITE_BIG, 1, "Schwartz Ghandi"),
    (LineType.WHITE_BIG, 1, "m4rkersm4sk"),
    (LineType.WHITE_BIG, 1, "Miepee"),
    (LineType.WHITE_BIG, 3, "Sharky"),
]

# Shortened from 462 lines to 308 lines
FUSION_STAFF_LINES = [
    (LineType.WHITE_BIG, 4, "ORIGINAL FUSION STAFF"),
    (LineType.BLUE, 1, "PRODUCER"),
    (LineType.WHITE, 5, "Izushi Takehiro"),
    (LineType.BLUE, 1, "CHIEF DIRECTOR"),
    (LineType.WHITE, 5, "Sakamoto Yoshio"),
    (LineType.BLUE, 1, "SYSTEM DIRECTOR"),
    (LineType.WHITE, 3, "Hosokawa Takehiko"),
    (LineType.BLUE, 1, "SCENARIO & STORY"),
    (LineType.WHITE, 3, "Sakamoto Yoshio"),
    (LineType.BLUE, 1, "GAME DESIGN"),
    (LineType.WHITE, 1, "Yamane Tomoyoshi"),
    (LineType.WHITE, 3, "Hosokawa Takehiko"),
    (LineType.BLUE, 1, "COURSE DESIGN"),
    (LineType.WHITE, 1, "Ueda Masani"),
    (LineType.WHITE, 3, "Nakada Ryuichi"),
    (LineType.BLUE, 1, "VISUAL DIRECTOR"),
    (LineType.WHITE, 3, "Yamane Tomoyoshi"),
    (LineType.BLUE, 1, "SAMUS DESIGN"),
    (LineType.WHITE, 3, "Sano Shinya"),
    (LineType.BLUE, 1, "SAMUS ORIGINAL DESIGN"),
    (LineType.WHITE, 3, "Kiyotake Hiroji"),
    (LineType.BLUE, 1, "ENEMY CHARACTER DESIGN"),
    (LineType.WHITE, 1, "Yamane Tomoyoshi"),
    (LineType.WHITE, 1, "Hirano Isao"),
    (LineType.WHITE, 1, "Sano Shinya"),
    (LineType.WHITE, 3, "Matsushita Tadashi"),
    (LineType.BLUE, 1, "BACKGROUND GRAPHIC DESIGN"),
    (LineType.WHITE, 1, "Morisawa Takayasu"),
    (LineType.WHITE, 3, "Miyamoto Fumiko"),
    (LineType.BLUE, 1, "GRAPHIC DESIGN"),
    (LineType.WHITE, 1, "Momose Hiroshi"),
    (LineType.WHITE, 3, "Sakiyama Chiharu"),
    (LineType.BLUE, 1, "PROGRAM DIRECTOR"),
    (LineType.WHITE, 3, "Yamano Katsuya"),
    (LineType.BLUE, 1, "SAMUS PROGRAMMING"),
    (LineType.WHITE, 3, "Katsuki Yoshinori"),
    (LineType.BLUE, 1, "ENEMY CHARACTER PROGRAMMING"),
    (LineType.WHITE, 3, "Yamano Katsuya"),
    (LineType.BLUE, 1, "SYSTEM PROGRAMMING"),
    (LineType.WHITE, 3, "Ozaki Nobuhiro"),
    (LineType.BLUE, 1, "CINEMA SCENE PROGRAMMING"),
    (LineType.WHITE, 3, "Nakae Eisaku"),
    (LineType.BLUE, 1, "TOOL PROGRAMMING"),
    (LineType.WHITE, 1, "Harada Takahiro"),
    (LineType.WHITE, 1, "Fukui Kota"),
    (LineType.WHITE, 1, "Katsuki Yoshinori"),
    (LineType.WHITE, 1, "Ozaki Nobuhiro"),
    (LineType.WHITE, 3, "Momose Hiroshi"),
    (LineType.BLUE, 1, "SOUND DIRECTOR"),
    (LineType.WHITE, 3, "Yamamoto Kenji"),
    (LineType.BLUE, 1, "MUSIC COMPOSITION"),
    (LineType.WHITE, 1, "Hamano Minako"),
    (LineType.WHITE, 3, "Fujiwara Akira"),
    (LineType.BLUE, 1, "SOUND EFFECTS & PROGRAMMING"),
    (LineType.WHITE, 3, "Fujii Takaya"),
    (LineType.BLUE, 1, "PACKAGE DESIGN"),
    (LineType.WHITE, 3, "Nakamichi Sachiko"),
    (LineType.BLUE, 1, "MANUAL DESIGN"),
    (LineType.WHITE, 1, "Nakamichi Sachiko"),
    (LineType.WHITE, 1, "Itani Kiyomi"),
    (LineType.WHITE, 3, "Takahashi Yasuko"),
    (LineType.BLUE, 1, "COORDINATION"),
    (LineType.WHITE, 3, "Harada Takahiro"),
    (LineType.BLUE, 1, "INTERNATIONAL COORDINATION"),
    (LineType.WHITE, 3, "Yamazaki Sakae"),
    (LineType.BLUE, 1, "DEBUG"),
    (LineType.WHITE, 6, "SUPER MARIO CLUB"),
    (LineType.BLUE, 1, "SPECIAL THANKS"),
    (LineType.WHITE, 10, "Matsumura Satoshi"),
    (LineType.RED, 2, "NOA ENGLISH LOCALIZATION"),
    (LineType.BLUE, 1, "LOCALIZATION MANAGEMENT"),
    (LineType.WHITE, 1, "Jeff Miller"),
    (LineType.WHITE, 3, "Leslie Swan"),
    (LineType.BLUE, 1, "LOCALIZATION"),
    (LineType.WHITE, 1, "Scot Ritchey"),
    (LineType.WHITE, 1, "Nathan Bihldorff"),
    (LineType.WHITE, 3, "Tim O-Leary"),
    (LineType.BLUE, 1, "ENGINEERING DEBUG"),
    (LineType.WHITE, 1, "Raychole L'Anett"),
    (LineType.WHITE, 1, "Robert Crombie"),
    (LineType.WHITE, 1, "Kirk Buchanan"),
    (LineType.WHITE, 2, "Yoshinobu Mantani"),
    (LineType.WHITE, 1, "Scott Callahan"),
    (LineType.WHITE, 1, "Don Dillinger"),
    (LineType.WHITE, 3, "Hisako Sakauchi"),
    (LineType.BLUE, 1, "SPECIAL THANKS"),
    (LineType.WHITE, 1, "Tatsumi Kimishima"),
    (LineType.WHITE, 1, "Mike Fukuda"),
    (LineType.WHITE, 13, "Hiroshi Kamada"),
    (LineType.BLUE, 1, "EXECUTIVE PRODUCER"),
    (LineType.WHITE, 22, "Iwata Satoru"),
    (LineType.COPYRIGHT1, 0, None),
    (LineType.COPYRIGHT2, 0, None),
    (LineType.COPYRIGHT3, 0, None),
    (LineType.COPYRIGHT4, 9, None),
    (LineType.END, 0, None),
]
