from enum import IntEnum


# In-between spaces are null values
class MusicLibrary(IntEnum):
    UNUSED_1 = 0x1  # Short track with mainly percussion

    AFTER_EVENT = 0x3
    SECTOR_1 = 0x4

    SECTOR_2 = 0x6
    SECTOR_3 = 0x7
    SECTOR_5 = 0x8
    SECTOR_4 = 0x9
    SECTOR_6 = 0xA
    NAVIGATION_ROOM = 0xB

    SECURITY_DATA_ROOM = 0xF
    ITEM_JINGLE = 0x10
    LOADING_SAVE = 0x11

    MESSAGE_POPUP = 0x14
    SA_X_APPEARANCE = 0x15

    SA_X_CHASE = 0x17
    BOSS_TENSION = 0x18
    ARACHNUS_BATTLE = 0x19
    ZAZABI_BATTLE = 0x1A
    BOX_BATTLE = 0x1B

    MAIN_DECK_AMBIENCE = 0x1E
    UNUSED_1F = 0x1F  # Combination of MAIN_DECK_AMBIENCE and TENSION
    UNUSED_20 = 0x20  # Dramatic track combined with MAIN_DECK_AMBIENCE

    SILENCE_1_SHIP = 0x2A
    TENSION = 0x2B
    MAIN_DECK_LIVELY = 0x2C
    OMEGA_METROID_DEFEATED = 0x2D
    OPERATIONS_DECK = 0x2E
    OPERATIONS_DECK_ELEVATOR_OFFLINE_SOUND_AND_AMBIENCE = 0x2F
    X_INVASION_DETECTION = 0x30
    SA_X_ELEVATOR = 0x31
    HEADING_TO_NIGHTMARE_RIDLEY = 0x32
    OPERATIONS_DECK_ELEVATOR_OFFLINE_SOUND = 0x33
    OPERATIONS_DECK_ELEVATOR_OFFLINE_AMBIENCE = 0x34
    MAIN_BOILER_COOLDOWN_MISSION = 0x35

    STATION_ESCAPE = 0x38

    OBJECTIVE_COMPLETE = 0x3B
    SECTOR_4_UNDERWATER = 0x3C

    SECTOR_4_UNDERWATER_UNUSED = 0x3E
    SERRIS_YAKUZA_BATTLE = 0x3F
    VARIA_CORE_X_BATTLE = 0x40
    NIGHTMARE_BATTLE = 0x41
    NEO_RIDLEY_BATTLE = 0x42
    CHOZO_STATUE_CORE_X_BATTLE = 0x43
    NETTORI_BATTLE = 0x44

    PRE_TITLE_END = 0x49
    TITLE = 0x4A

    SA_X_BATTLE = 0x51

    EPILOGUE_END = 0x53

    ENDING = 0x55
    EPILOGUE = 0x56
    DISQUIETING = 0x57
    SHOCK = 0x58
    SILENCE_1 = 0x59
    MAIN_BOILER_OVERHEATING = 0x5A
    FINAL_ORDER = 0x5B
    SILENCE_2 = 0x5C
    INTRIGUE = 0x5D
    UNUSED_5E = 0x5E  # Suspenseful track
    UNEASE = 0x5F
