from mars_patcher.constants.credits import LineType

MARS_CREDITS = [
    (LineType.WHITE_BIG, 4, "MARS Development"),
    (LineType.BLUE, 2, "PROGRAMMING"),
    (LineType.WHITE_BIG, 1, "biospark"),
    (LineType.WHITE_BIG, 1, "cluekitty"),
    (LineType.WHITE_BIG, 1, "Zarakava"),
    (LineType.WHITE_BIG, 1, "Miepee"),
    (LineType.WHITE_BIG, 1, "JeffGainsNGames"),
    (LineType.WHITE_BIG, 3, "duncathan_salt"),
    (LineType.BLUE, 2, "GRAPHICS"),
    (LineType.WHITE_BIG, 1, "<person 1>"),
    (LineType.WHITE_BIG, 3, "<person 2>"),
    # (LineType.BLUE, 2, "MUSIC"),
    # (LineType.WHITE_BIG, 1, "<person 1>"),
    # (LineType.WHITE_BIG, 3, "<person 2>"),
    (LineType.BLUE, 2, "SPECIAL THANKS TO"),
    (LineType.WHITE_BIG, 1, "Yohann"),
    (LineType.WHITE_BIG, 4, "And contributions from others"),
]

RDV_CREDITS = [
    (LineType.WHITE_BIG, 2, "Randovania"),
    (LineType.BLUE, 2, "INTEGRATION"),
    (LineType.WHITE_BIG, 1, "JeffGainsNGames"),
    (LineType.WHITE_BIG, 3, "<person 2>"),
    (LineType.BLUE, 2, "LOGIC DATABASE"),
    (LineType.WHITE_BIG, 1, "<person 1>"),
    (LineType.WHITE_BIG, 3, "<person 2>"),
]

# Shortened from 347 lines to 201 lines
ZM_STAFF_LINES = [
    (LineType.WHITE_BIG, 4, "ORIGINAL ZERO MISSION STAFF"),
    (LineType.BLUE, 1, "PRODUCER"),
    (LineType.WHITE, 3, "Izushi Takehiro"),
    (LineType.BLUE, 1, "DIRECTOR"),
    (LineType.WHITE, 3, "Sakamoto Yoshio"),
    (LineType.BLUE, 1, "SAMUS DESIGN"),
    (LineType.WHITE, 3, "Kiyotake Hiroji"),
    (LineType.BLUE, 1, "COURSE DESIGN"),
    (LineType.WHITE, 1, "Ueda Masani"),
    (LineType.WHITE, 1, "Hosokawa Takehiko"),
    (LineType.WHITE, 3, "Nakada Ryuichi"),
    (LineType.BLUE, 1, "GRAPHIC DESIGN"),
    (LineType.WHITE, 1, "Morisawa Takayasu"),
    (LineType.WHITE, 1, "Matsushita Tadashi"),
    (LineType.WHITE, 1, "Miyamoto Fumiko"),
    (LineType.WHITE, 1, "Sakiyama Chiharu"),
    (LineType.WHITE, 1, "Furuta Norikatsu"),
    (LineType.WHITE, 3, "Momose Hiroshi"),
    (LineType.BLUE, 1, "PROGRAMMING"),
    (LineType.WHITE, 1, "Yamano Katsuya"),
    (LineType.WHITE, 1, "Katsuki Yoshinori"),
    (LineType.WHITE, 1, "Ozaki Nobuhiro"),
    (LineType.WHITE, 1, "Kawase Tomohiro"),
    (LineType.WHITE, 3, "Shimizu Hideaki"),
    (LineType.BLUE, 1, "MUSIC COMPOSITION"),
    (LineType.WHITE, 1, "Yamamoto Kenji"),
    (LineType.WHITE, 3, "Hamano Minako"),
    (LineType.BLUE, 1, "SOUND EFFECT & PROGRAMMING"),
    (LineType.WHITE, 3, "Fujii Takaya"),
    (LineType.BLUE, 1, "PACKAGE & MANUAL DESIGN"),
    (LineType.WHITE, 1, "Inoue Yasuo"),
    (LineType.WHITE, 1, "Nakamichi Sachiko"),
    (LineType.WHITE, 3, "Takahashi Yasuko"),
    (LineType.BLUE, 1, "COORDINATION"),
    (LineType.WHITE, 3, "Harada Takahiro"),
    (LineType.BLUE, 1, "DEBUG"),
    (LineType.WHITE, 3, "SUPER MARIO CLUB"),
    (LineType.BLUE, 1, "SPECIAL THANKS"),
    (LineType.WHITE, 1, "Fukui Kota"),
    (LineType.WHITE, 1, "Nishimura Kentaro"),
    (LineType.WHITE, 1, "Nakano Takao"),
    (LineType.WHITE, 1, "Osawa Kazuyoshi"),
    (LineType.WHITE, 1, "Furuta Takeshi"),
    (LineType.WHITE, 1, "Saeki Naoko"),
    (LineType.WHITE, 3, "Tanaka Hirokazu"),
    (LineType.BLUE, 1, "NORTH AMERICAN LOCALIZATION"),
    (LineType.WHITE, 1, "Nate Bihldorff"),
    (LineType.WHITE, 3, "Bill Trinen"),
    (LineType.BLUE, 1, "LOCALIZATION MANAGEMENT"),
    (LineType.WHITE, 1, "Jeff Miller"),
    (LineType.WHITE, 3, "Leslie Swan"),
    (LineType.BLUE, 1, "NOA PRODUCT TESTING DEPARTMENT"),
    (LineType.WHITE, 1, "Yoshinobu Mantani"),
    (LineType.WHITE, 1, "Kyle Hudson"),
    (LineType.WHITE, 1, "Eric Bush"),
    (LineType.WHITE, 1, "Randy Shoemake"),
    (LineType.WHITE, 1, "Rich Richardson"),
    (LineType.WHITE, 1, "Thomas Hertzog"),
    (LineType.WHITE, 1, "Michael Leslie"),
    (LineType.WHITE, 1, "Kathy Huguenard"),
    (LineType.WHITE, 1, "David Hunziker"),
    (LineType.WHITE, 1, "Chris Needham"),
    (LineType.WHITE, 3, "Mika Kurosawa"),
    (LineType.BLUE, 1, "SPECIAL THANKS"),
    (LineType.WHITE, 1, "Mike Fukuda"),
    (LineType.WHITE, 3, "Tatsumi Kimishima"),
    (LineType.BLUE, 1, "EXECUTIVE PRODUCER"),
    (LineType.WHITE, 18, "Iwata Satoru"),
    (LineType.COPYRIGHT1, 0, None),
    (LineType.COPYRIGHT2, 0, None),
    (LineType.COPYRIGHT3, 0, None),
    (LineType.COPYRIGHT4, 8, None),
    (LineType.END, 0, None),
]
