from enum import IntEnum


# In-between spaces are null values
class MusicLibrary(IntEnum):
    BRINSTAR = 0x1
    TITLE_SCREEN = 0x2
    SAVE_ELEVATOR_ROOM = 0x3
    INTRO = 0x4
    CHOZO_STATUE_HINT = 0x5
    NORFAIR = 0x6
    KRAID = 0x7
    ESCAPE = 0x8
    FILE_SELECT = 0x9
    STATUE_ROOM = 0xA
    BOSS_KILLED = 0xB
    MAP_ROOM = 0xC
    CHOZO_RUINS_DEPTH = 0xD
    CHOZO_RUINS = 0xE
    CHOZO_RUINS_LIGHT = 0xF
    RIDLEY_IN_SPACE = 0x10
    RIDLEY_LANDING = 0x11
    CHOZO_STATUE_HINT_DELAY = 0x12
    GETTING_FULLY_POWERED_SUIT_CUTSCENE = 0x13
    ESCAPING_ZEBES_CUTSCENE = 0x14
    CHOZO_VOICE_1 = 0x15
    CHOZO_VOICE_2 = 0x16
    BEFORE_RUINS_TEST_UNUSED = 0x17
    ELEVATOR_ROOM = 0x18
    BRINSTAR_REMIX = 0x19
    ESCAPE_SUCCESFUL = 0x1A
    CREDITS = 0x1B
    STATUE_ROOM_OPENED = 0x1C

    RIDLEY = 0x32

    KRAID_BATTLE_WITH_INTRO = 0x34
    RIDLEY_BATTLE = 0x35
    LOADING_JINGLE = 0x36
    GETTING_ITEM_JINGLE = 0x37

    INTRO_MOTHER_BRAIN = 0x39
    GETTING_TANK_JINGLE = 0x3A
    TOURIAN = 0x3B
    WORMS_BATTLE = 0x3C
    MOTHER_BRAIN_BATTLE = 0x3D
    CATTERPILLARS_BATTLE = 0x3E
    IMAGO_COCOON_BATTLE = 0x3F
    IMAGO_BATTLE = 0x40
    MECHA_RIDLEY_BATTLE = 0x41
    GETTING_UNKNOWN_ITEM_JINGLE = 0x42
    RUINS_TEST_BATTLE_WITH_INTRO = 0x43
    ENTERING_TOURIAN_CUTSCENE = 0x44
    ALARM_ACTIVATED = 0x45
    STEALTH = 0x46

    ENTERING_NORFAIR_CUTSCENE = 0x48
    CHOZODIA_DETECTED = 0x49
    GETTING_FULLY_POWERED_SUIT_JINGLE = 0x4A
    KRAID_BATTLE = 0x4B
    RIDLEY_BATTLE_2 = 0x4C
    MECHA_RIDLEY_BATTLE_2 = 0x4D
    RUINS_TEST_BATTLE = 0x4E
    CATTERPILLARS_BATTLE_2 = 0x4F
    CRATERIA = 0x50

    GAME_OVER = 0x53

    CHOZODIA_SURFACE = 0x5A
    MAP_ROOM_2 = 0x5B
    SAVE_ELEVATOR_ROOM_2 = 0x5C
    BEFORE_RUINS_TEST_ROOM = 0x5D
    STEALTH_2 = 0x5E
